#!/bin/bash

tput init
#
# Language-based variable assignment for script directory path
# This serves as a Rosetta Stone for developers,
# allowing them to use the variable name they are most comfortable with.

# allows CTRL c to exit
trap "exit" INT TERM
[[ $EUID != 0 ]] && exec sudo "$0" "$@"
#
# Get the script directory
script_dir="$(dirname "$0")"

[[ -d "$script_dir/../tools" ]] && tools_dir="$script_dir/../tools"
[[ ! -d "$script_dir/../lib" && -n "$tools_dir" ]] && echo -e "Please run\nbash "$tools_dir/config-assemble.sh" to build the lib directory\n" && exit 1 

# 'whiptail' is a simple dialog box utility that works well with Bash. It doesn't have all the features of some other dialog box utilities, but it does everything we need for this script.
[[ -x "$(command -v whiptail)" ]] && DIALOG="whiptail"

. "$tools_dir/dev/developer_checkpoint.sh"
set_checkpoint start
set_checkpoint mark "Initializing script" time


# Define the lib directory one level up from the script directory
lib_dir="$script_dir/../lib/armbian-config"
doc_dir="$script_dir/../share/doc/armbian-config"
json_file="$lib_dir/config.jobs.json"

#
# Load The Bash procedure Objects
json_data=$(<"$json_file")

#
# Prepare the module options array
declare -A module_options
set_checkpoint mark "Paths set" time
#
# Load configng core functions and module options array

source "$lib_dir/config.functions.sh"
set_checkpoint mark "Base lib loaded" time
set_runtime_variables
set_checkpoint mark "Runtime variables set" time ;
check_distro_status
set_checkpoint mark "Distro check done" time ;

source "$lib_dir/config.docs.sh"
set_checkpoint mark "Docs..." time ;
source "$lib_dir/config.system.sh"
set_checkpoint mark "System Modules Loaded..." time ;
source "$lib_dir/config.network.sh"
set_checkpoint mark "Network Modules Loaded ..." time ;
source "$lib_dir/config.software.sh"
set_checkpoint mark "Software Modules Loaded..." time ;
#
# Loads the variables from beta armbian-config for runtime handling

source "$lib_dir/config.runtime.sh"
set_checkpoint mark "Runtime conditions..." time ;

clear

case "$1" in
"--help")
	if [[ -n "$2" ]]; then
		see_cmd_list "$2"
		echo ""
		exit 0
	fi

	echo "Usage:  armbian-config --[option]
     Options:
     --help [category]   Use [category] to filter specific menu options.
     --cmd  [option]     Run a command from the menu (simple)
     --api  [option]     Run a helper command        (advanced)
     --doc               Generate the README.md file 

     Examples:
     armbian-config --help [cmd||System||Software||Network||Localisation]
     armbian-config --cmd help 
     armbian-config --api help
"
	exit 0
	;;
"--doc")
	generate_readme
	exit 0
	;;
"--cmd")
	INPUTMODE="cmd"
	shift
	if [[ -z "$1" || "$1" == "help" ]]; then
		see_cmd_list
		exit 0
	fi

	args=$(sanitize_input "$@")
	execute_command "$args"
	exit 0
	;;
"--api")
	shift
	if [[ -z "$1" || "$1" == "help" ]]; then
		see_use
		exit 0
	fi
	option="$1"
	shift
	args=$(sanitize_input "$@")
	# echo -e "\"$option\" \"$args\""
	"$option" "$args"
	exit 0
	;;
*)
	if [[ $EUID != 0 ]]; then
		echo -e "error: Exiting \nTry: 'sudo armbian-config'\n or: 'armbian-config --help' for More info\n\n"
		exit 0
	fi
	;;
esac

set_checkpoint stop

generate_top_menu "$json_data"

#
# Exit the script with a success status code

#
# Show about this tool on exit
about_armbian_configng

#set_checkpoint show
exit 0
