#!/bin/bash

# Ensure the script is run with root privileges 
[[ $EUID != 0 ]] && exec sudo "$0" "$@"

# Initialize data base (associative array for module options)
declare -A module_options

# Default settings (do not change here) 
INPUTMODE="cmd" 

# Conditional settings
if [[ "$1" == "--api" || "$1" == "--doc" ]]; then
    UXMODE="cmd"
elif [[ -z "$1" || "$1" == "--cmd" ]]; then
    UXMODE="tui"
fi

#UXMODE="tui"
#[[ "$1" == "--api" ]] && UXMODE="cmd" ;
script_dir="$(dirname "$0")"

# Conditional settings

[[ -d "$script_dir/../tools" ]] && tools_dir="$script_dir/../tools"
[[ ! -d "$script_dir/../lib" && -n "$tools_dir" ]] && echo -e "Please run\nbash "$tools_dir/config-assemble.sh" to build the lib directory\n" && exit 1 

[[ -x "$(command -v whiptail)" ]] && DIALOG="whiptail"

# Load and run timer
# see --api set_checkpoint help for more info 
#. "$tools_dir/dev/messages_checkpoint.sh"
# Iterate over each .sh file in the specified directory and source it
for file in "$tools_dir/dev"/*.sh; do
  . "$file"
done
#
set_checkpoint start
set_checkpoint mark "Initializing complete" time


# Define the lib directory one level up from the script directory
lib_dir="$script_dir/../lib/armbian-config"
doc_dir="$script_dir/../share/doc/armbian-config"
json_file="$lib_dir/config.jobs.json"
set_checkpoint mark "File paths set" time
#
# Load UX data
json_data=$(<"$json_file")
set_checkpoint mark "UX Data loaded" time

source "$lib_dir/config.runtime.sh"
set_checkpoint mark "Runtime conditions set" time ;
#
# Load configng core functions and module options array
source "$lib_dir/config.functions.sh"
set_checkpoint mark "Main library loaded" time

set_runtime_variables
set_checkpoint mark "Runtime variables set" time ;

set_checkpoint mark "$(check_distro_status)" time ;

source "$lib_dir/config.docs.sh"
set_checkpoint mark "Docs..." time ;

source "$lib_dir/config.system.sh"
set_checkpoint mark "System Modules Loaded" time ;

source "$lib_dir/config.network.sh"
set_checkpoint mark "Network Modules Loaded" time ;

source "$lib_dir/config.software.sh"
set_checkpoint mark "Software Modules Loaded" time ;



case "$1" in
"--help")
	if [[ -n "$2" ]]; then
		see_cmd_list "$2"
		echo ""
		exit 0
	fi

	echo "Usage:  armbian-config --[option]
     Options:
     --help [category]   Use [category] to filter specific menu options.
     --cmd  [option]     Run a command from the menu (simple)
     --api  [option]     Run a helper command        (advanced)
     --doc               Generate the README.md file 

     Examples:
     armbian-config --help [cmd||System||Software||Network||Localisation]
     armbian-config --cmd help 
     armbian-config --api help
"
	exit 0
	;;
"--doc")
	generate_readme
	exit 0
	;;
"--cmd")
	INPUTMODE="cmd"
    UXMODE="tui"
	shift
	if [[ -z "$1" || "$1" == "help" ]]; then
		see_cmd_list
		exit 0
	fi

	args=$(sanitize_input "$@")
	execute_command "$args"
	exit 0
	;;
"--api")
    INPUTMODE="cmd"
    UXMODE="cmd"
	shift
	if [[ -z "$1" || "$1" == "help" ]]; then
		see_use
		exit 0
	fi
	option="$1"
	shift
	args="$@"
	# echo -e "\"$option\" \"$args\""
	"$option" "$args"
	exit 0
	;;
*)
	if [[ $EUID != 0 ]]; then
		echo -e "error: Exiting \nTry: 'sudo armbian-config'\n or: 'armbian-config --help' for More info\n\n"
		exit 0
	fi
	UXMODE="tui"
	set_menu_runtime
	set_checkpoint mark "Menu Runtime updated" time ;
	clear
	set_checkpoint stop
	generate_top_menu "$json_data"
	set_checkpoint show
	;;
esac



# move curser to last line for dialoge
tput cup $(($(tput lines) - 1)) 0
#
# FOO="$(/home/tearran/configng/tools/armbian-config-dev --api set_checkpoint help)" && echo -e "~~~\n$FOO\n~~~"  > "./tools/include/markdown/set_checkpoint-footer.sh"

#set_checkpoint show
exit 0
