name: Debian package
#
# Description
#

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:

  check-owner:
    runs-on: ubuntu-latest
    steps:
    - name: Fail if not in armbian repo
      run: if [ "$GITHUB_REPOSITORY_OWNER" != "armbian" ]; then exit 1; fi

  Debian:
    needs: check-owner
    uses: armbian/scripts/.github/workflows/pack-debian.yml@master
    with:
      matrix: "all:jammy"
      maintainer: "Igor Pecovnik <igor@armbian.com>"
      package: "configng"
      licence: "GPL 2.0"
      homepage: "https://www.armbian.com"
      section: "default"
      priority: "optional"
      depends: "bash whiptail jq"
      description: "Configng"

    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_KEY1 }}
      PASSPHRASE: ${{ secrets.GPG_PASSPHRASE1 }}