on: push
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'Tearran' }}
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: Set TERM environment variable
      run: echo "TERM=xterm" >> $GITHUB_ENV

    - name: Install ShellCheck
      run: sudo apt-get install pandoc git shellcheck

    - name: Run ShellCheck
      run: |
        ret=0
        for file in $(find . -type f -name "*.sh"); do
          shellcheck --severity=error $file || ret=$?
        done
        exit $ret 

    - name: Generate website 
      run: ./bin/armbian-configng --doc

    - name: Checkout Wiki
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}.wiki
        path: .wiki
        
    - name: Update Wiki
      run: |
        cp -r share/doc/armbian-configng/* .wiki/
        cd .wiki
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update Wiki"
        git push

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.SERVER_HOST}}  # replace with your server
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}     
        server-dir: / # replace with your server directory
        local-dir: share/doc/armbian-configng/ # replace with your local directory