name: Update Documentation

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, review_requested]

jobs:
  update-doc:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git
    
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        ref: main

    - name: Run documentation update script
      run: |
        chmod +x ./bin/armbian-configng
        ./bin/armbian-configng --doc

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update README after PR merge"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
